<?php
session_start();
if($_SERVER["REQUEST_METHOD"] == "POST") {
    require_once 'db.php';

    $application_date = date("Y-m-d H:i:s");
    $fname = $_POST['fname'];
    $lname = $_POST['lname'];
    $address = $_POST['address'];
    $birthdate = $_POST['birthdate'];
    $birthplace = $_POST['birthplace'];
    $weight = $_POST['weight'];
    $height = $_POST['height'];
    $civil_status = $_POST['status'];
    $tin = $_POST['tin'];
    $sss = $_POST['sss'];
    $ec_name = $_POST['ec_name'];
    $ec_address = $_POST['ec_address'];
    $ec_contact = $_POST['ec_contact'];
    $contact_num = $_POST['contact_num'];
    $pickup = $_POST['pickup'];
    $user_id = $_SESSION['acc_id'];

    // Insert into documents table
    $sql = "INSERT INTO documents (doc_type, first_name, last_name, address, birthdate, civil_status, ec_name, ec_address, ec_contact, SSSno, height, weight, tin, birthplace, application_date, contact_num, pickup) 
            VALUES ('ID', '$fname', '$lname', '$address', '$birthdate', '$civil_status', '$ec_name', '$ec_address', '$ec_contact', '$sss', '$height', '$weight', '$tin', '$birthplace', '$application_date', '$contact_num','$pickup')";


    if ($conn->query($sql) === TRUE) {
    // Get the doc_id generated by the documents table insert
    $doc_id = $conn->insert_id;

    // Generate the control number using the doc_id
    $random_number = str_pad(rand(0, 9999), 4, '0', STR_PAD_LEFT);
    $control_number = "837-" . str_pad($doc_id, 4, '0', STR_PAD_LEFT);

    // Update the documents table with the control number
    $sql = "UPDATE documents SET control_number = '$control_number' WHERE doc_id = $doc_id";

    if ($conn->query($sql) === TRUE) {
        // Insert into doc_req table
        $status = 'Pending';
        $sql = "INSERT INTO doc_req (doc_id, status, acc_id)
                VALUES ('$doc_id', '$status', '$user_id')";

        if ($conn->query($sql) === TRUE) {
            echo "<script>alert('Successfully requested.');</script>";
            echo "<script>window.location.assign('../brgy_id.php');</script>";
            exit();
        } else {
            echo "Error: " . $sql . "<br>" . $conn->error;
        }
    } else {
        echo "Error: " . $sql . "<br>" . $conn->error;
    }
} else {
    echo "Error: " . $sql . "<br>" . $conn->error;
}

}

?>
